### PR TITLE
Update to the version from pyre-check 0.0.56

### PR DESCRIPTION
**Pull request by bnavigator**
As a follow up to #16, here is a PR updating the codebase to the version of hack_parallel that is bundled into pyre-check 0.0.56

Note that I have no Ocaml experience at all. I could be completely wrong.

I kept the interface module and modified the `destroy`  function.

### CODE REVIEW

**Comment by rvantonder** [comment]
Hey @bnavigator! Thanks for this. Generally it's nice to keep up with Pyre's upstream files, so if this compiles it's probably fine. But I do need some time to check over it before I can put it upstream in opam.

About #16, it's a bit unfortunate that this would depend on all of `Core` (it's a pretty big library) simply because of `Unix.localtime`. I may tinker to avoid just that part.

**Comment by rvantonder** [comment]
To be more specific, I'll look into this by Oct 3.

**Comment by bnavigator** [comment]
Awesome! No hurry by the way.

Note that with just the minimal `Unix.localtime` fix in #16, there are some deprecation messages in the compile log that more stuff moved into `Core`.

**Comment by rvantonder** [comment]
Sorry this has taken a while. I've looked at the changes and will need more time to fix some things up, it will currently break the previous interface, the reason is there isn't a one-to-one correspondence with upstream pyre library.

**Pull request closed without merging**
